### PR TITLE
Add a few keys to the UI

### PR DESCRIPTION
**Pull request by tkling**
This totally started out as a stab in the dark. If more needs to be added here to make this happen let me know and I'll take a stab in the dark at that too :) I have verified that the keys I've added are available on the UI, haven't used it to generate a dfu.bin for a test flash though.

* adds space, tab, enter, escape, and backspace to the 'standard' UI group
* makes the JSON that is shown via the Version button real parse-able JSON :)
* adds the `controller/` dir to .gitignore since that dir doesn't end up in KiiConf's source control repo

### CODE REVIEW

**Comment by sigboe** [comment]
I like this pull request!

**Comment by haata** [comment]
Sorry for the delay, pull request looks awesome. I'm flying back from NZ today so I should be a lot more responsive.

**Comment by sigboe** [comment]
@haata are you going to update the configurator on input.club to the newest version?

**Comment by haata** [comment]
Sorry about that, will do right now.

Done.

**Comment by sigboe** [comment]
Thanks :smile:

**Pull request merged**
